repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-zero]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: git-add-changes
        name: Git Add Changes
        entry: git add .
        language: system
        pass_filenames: false
        always_run: true
